
site_name: GQLAlchemy Documentation

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: 'material'
  logo: 'assets/memgraph-logo.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono' 
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: 'custom'
    accent: 'custom'
nav:
  - Getting Started: 'index.md'
  - Installation: 'installation.md'
  - Import Data: 'import-data.md'
  - How-To Guides:
    - Overview: 'how-to-guides/overview.md'
    - Use object graph mapper: 'how-to-guides/ogm.md'
    - Use query builder: 'how-to-guides/query-builder.md'
    - Manage streams:
      - Kafka Streams: 'how-to-guides/streams/kafka-streams.md'
      - Pulsar Streams: 'how-to-guides/streams/pulsar-streams.md'
    - Import data from different sources:
      - Table to Graph Importer: 'how-to-guides/loaders/import-table-data-to-graph-database.md'
      - Custom File System Importer: 'how-to-guides/loaders/make-a-custom-file-system-importer.md'
    - Manage instances:
      - Memgraph Docker Instance: 'how-to-guides/instance-runner/memgraph-docker-instance.md'
      - Memgraph Binary Instance: 'how-to-guides/instance-runner/memgraph-binary-instance.md'
    - Triggers: 'how-to-guides/triggers/triggers.md'
    - On-Disk Storage: 'how-to-guides/on-disk-storage/on-disk-storage.md'
    - Graph Projection: 'how-to-guides/query-builder/graph-projection.md'
    - Translate Python graphs:
      - Import Python Graphs: 'how-to-guides/translators/import-python-graphs.md'
      - Export Python Graphs: 'how-to-guides/translators/export-python-graphs.md'
  - Reference:
    - Overview: 'reference/gqlalchemy/overview.md'
    - Connection: 'reference/gqlalchemy/connection.md'
    - Disk Storage: 'reference/gqlalchemy/disk_storage.md'
    - Exceptions: 'reference/gqlalchemy/exceptions.md'
    - Instance Runner: 'reference/gqlalchemy/instance_runner.md'
    - Loaders: 'reference/gqlalchemy/loaders.md'
    - Models: 'reference/gqlalchemy/models.md'
    - Transformations: 'reference/gqlalchemy/transformations.md'
    - Utilities: 'reference/gqlalchemy/utilities.md'
    - Graph Algorithms:
      - Integrated Algorithms: 'reference/gqlalchemy/graph_algorithms/integrated_algorithms.md'
      - Query Builder: 'reference/gqlalchemy/graph_algorithms/query_builder.md'
      - Query Modules: 'reference/gqlalchemy/graph_algorithms/query_modules.md'
    - Query Builders:
      - Declarative Base: 'reference/gqlalchemy/query_builders/declarative_base.md'
      - Memgraph Query Builder: 'reference/gqlalchemy/query_builders/memgraph_query_builder.md'
    - Transformations:
      - Export:
        - Graph Transporter: 'reference/gqlalchemy/transformations/export/graph_transporter.md'
        - Transporter: 'reference/gqlalchemy/transformations/export/transporter.md'
      - Importing:
        - Graph Importer: 'reference/gqlalchemy/transformations/importing/graph_importer.md'
        - Loaders: 'reference/gqlalchemy/transformations/importing/loaders.md'
      - Translators:
        - DGL Translator: 'reference/gqlalchemy/transformations/translators/dgl_translator.md'
        - NX Translator: 'reference/gqlalchemy/transformations/translators/nx_translator.md'
        - PyG Translator: 'reference/gqlalchemy/transformations/translators/pyg_translator.md'
        - Translator: 'reference/gqlalchemy/transformations/translators/translator.md'
    - Vendors:
      - Database Client: 'reference/gqlalchemy/vendors/database_client.md'
      - Memgraph: 'reference/gqlalchemy/vendors/memgraph.md'
      - Neo4j: 'reference/gqlalchemy/vendors/neo4j.md'
  - Under the Hood:
    - Overview: 'under-the-hood/overview.md'
    - Python Graph Translators: 'under-the-hood/python-graph-translators.md'
  - Changelog: 'changelog.md'

repo_name: 'memgraph/gqlalchemy'
repo_url: 'https://github.com/memgraph/gqlalchemy'
extra_css:
  - stylesheets/extra.css
